import type { Department, LifecycleStage } from "@prisma/client";

/**
 * Default checklist seeded onto every new FranchiseProject (one Task per
 * title, per stage) — transcribed from the franchise lifecycle tracker
 * sheet (2026-09-18). Extra tasks beyond this list are added the normal way
 * (NewTaskForm), this is only the starting checklist.
 */
export const STAGE_TASK_TEMPLATES: Record<LifecycleStage, string[]> = {
  SALES_FRANCHISE_ACQUISITION: [
    "Franchise Lead Generated",
    "Lead Qualification",
    "Introductory Call",
    "Brand Presentation Shared",
    "Initial Investment Discussion",
    "Discovery Call",
    "Director Concall",
    "Financial Qualification",
    "Gurgaon Office Meeting",
    "Restaurant Visit",
    "Food Tasting",
    "Commercial Negotiation",
    "Territory Discussion",
    "Franchise Approval",
    "LOI Signoff",
  ],
  LOCATION_ACQUISITION: [
    "Location Shared by Franchisee",
    "Market Research",
    "Competition Mapping",
    "Footfall Analysis",
    "Revenue Projection",
    "Site Inspection",
    "Technical Feasibility",
    "Rental Benchmarking",
    "Landlord Negotiation",
    "Commercial Finalization",
    "Token Exchange",
    "Draft Lease Review",
    "Lease Agreement Execution",
  ],
  LEGAL_COMPLIANCE: [
    "Franchise Company Formation",
    "PAN Registration",
    "TAN Registration",
    "GST Registration",
    "Current Account Opening",
    "Franchise Agreement Drafting",
    "Digital Signing (Leegality)",
    "Security Deposit Collection",
    "Franchise Fee Collection",
    "NACH Mandate Setup",
    "Royalty Setup",
    "Vendor Portal Access",
  ],
  PROJECT_HANDOVER: [
    "Project Manager Assigned",
    "CRM Project Creation",
    "WhatsApp Project Group Creation",
    "Kickoff Meeting",
    "Project Timeline Shared",
    "Responsibility Matrix Shared",
    "Project Documentation Handover",
    "Budget Alignment Meeting",
    "Vendor Coordination Meeting",
    "Stage-wise Approval Calendar",
  ],
  DESIGN: [
    "Site Measurement",
    "Architectural Layout",
    "Kitchen Layout",
    "HVAC Layout",
    "Electrical Layout",
    "Plumbing Layout",
    "Ceiling Layout",
    "Lighting Layout",
    "Furniture Layout",
    "Branding Layout",
    "Civil Drawings",
    "3D Renders",
    "Design Approval",
  ],
  BOQ_PROCUREMENT: [
    "Auto BOQ Generation",
    "Budget Estimation",
    "BOQ Approval",
    "Payment Demand Raised",
    "Payment Received",
    "Purchase Order Generation",
    "Vendor Allocation",
    "Procurement Planning",
    "Delivery Schedule Finalization",
    "Procurement Approval",
  ],
  CONSTRUCTION_EXECUTION: [
    "Site Handover",
    "Civil Work",
    "Flooring Work",
    "Tiling Work",
    "Plumbing Work",
    "Electrical Work",
    "Ceiling Installation",
    "HVAC Installation",
    "Furniture Installation",
    "Kitchen Installation",
    "Branding Installation",
    "Deep Cleaning",
    "Snag List",
    "Snag Closure",
  ],
  LICENSING: [
    "FSSAI License",
    "Trade License",
    "Fire NOC",
    "Pollution NOC",
    "Music License",
    "GST Verification",
    "Labour Registration",
    "Shop & Establishment Registration",
    "Local Municipal Approvals",
    "License Compliance Audit",
  ],
  OPERATIONS_PREPARATION: [
    "Staff Hiring",
    "Staff Documentation",
    "Uniform Distribution",
    "Kitchen Trial",
    "Recipe Training",
    "SOP Training",
    "Billing Training",
    "Customer Service Training",
    "Fire Safety Training",
    "Mock Service",
    "Trial Run",
  ],
  TECHNOLOGY_DEPLOYMENT: [
    "POS Installation",
    "Petpooja Setup",
    "Menu Upload",
    "Swiggy Integration",
    "Zomato Integration",
    "QR Ordering Setup",
    "Loyalty Software Setup",
    "Billing Configuration",
    "Royalty Dashboard Setup",
    "CCTV Integration",
    "Attendance System",
    "Store Management App",
    "WhatsApp Automation",
    "SMS Automation",
  ],
  PRE_LAUNCH_MARKETING: [
    "Google Business Profile",
    "Instagram Page Creation",
    "Facebook Page Creation",
    "Influencer Shortlisting",
    "Professional Photoshoot",
    "Reel Shoot",
    "Hoardings & Outdoor Branding",
    "Local PR Activation",
    "Society & Community Marketing",
    "Opening Offers",
    "CRM Campaign",
    "WhatsApp Campaign",
    "Email Campaign",
  ],
  GRAND_LAUNCH: [
    "VIP Guest List",
    "Invite Distribution",
    "Influencer Event",
    "Ribbon Cutting Ceremony",
    "Live Coverage",
    "Launch Offers Activation",
    "Press Coverage",
    "Franchise Handover",
    "Operations Go-Live",
    "Launch Day Audit",
  ],
  POST_OPENING: [
    "Daily Sales Monitoring",
    "Daily P&L Tracking",
    "Store Audit",
    "Food Audit",
    "Hygiene Audit",
    "Marketing Review",
    "Royalty Collection",
    "NACH Verification",
    "Franchise Support",
    "Monthly Business Review",
    "Expansion Planning",
    "Quarterly Performance Review",
    "Annual Growth Strategy",
  ],
};

/**
 * Default Task.module for auto-seeded tasks in each stage — a best-fit
 * mapping onto the existing Department taxonomy (role-departments.ts), not a
 * new taxonomy. ADMIN/MANAGEMENT always retain full override access
 * (permissions.ts hasFullOverride) regardless of this default.
 */
export const STAGE_DEFAULT_DEPARTMENT: Record<LifecycleStage, Department> = {
  SALES_FRANCHISE_ACQUISITION: "SALES",
  LOCATION_ACQUISITION: "PROPERTY",
  LEGAL_COMPLIANCE: "LEGAL",
  PROJECT_HANDOVER: "PROJECTS",
  DESIGN: "INTERIORS",
  BOQ_PROCUREMENT: "PROCUREMENT",
  CONSTRUCTION_EXECUTION: "PROJECTS",
  LICENSING: "LEGAL",
  OPERATIONS_PREPARATION: "OPERATIONS",
  TECHNOLOGY_DEPLOYMENT: "OPERATIONS",
  PRE_LAUNCH_MARKETING: "MARKETING",
  GRAND_LAUNCH: "MARKETING",
  POST_OPENING: "OPERATIONS",
};
