import type { Department, LifecycleStage } from "@prisma/client";

export interface OpsProgressTaskTemplate {
  category: string;
  title: string;
  lifecycleStage: LifecycleStage;
  module: Department;
}

/**
 * BOQ/Ops master checklist (plan.md section 9, 2026-09-21) -- one entry per
 * real line item from boq_ops_master_checklist.csv (the founder's BOQ +
 * Operations_List master reference sheets), cleaned/classified and reviewed
 * with Apoorv before shipping (duplicate/junk/costing rows dropped -- see
 * plan.md section 9 for the full before/after count). Seeded the same way
 * STAGE_TASK_TEMPLATES is: one Task per entry, auto-created on every new
 * project. `category` (not `module`) is the trade/department roll-up axis
 * (see category-progress.ts) -- `module` still drives RBAC as usual.
 */
export const OPS_PROGRESS_TASK_TEMPLATES: OpsProgressTaskTemplate[] = [
  { category: "Interior", title: "Site Visit for Measurements", lifecycleStage: "DESIGN", module: "INTERIORS" },
  { category: "Interior", title: "Regular Visits", lifecycleStage: "DESIGN", module: "INTERIORS" },
  { category: "Interior", title: "Wall-to-Wall Concept & Mood Board", lifecycleStage: "DESIGN", module: "INTERIORS" },
  { category: "Interior", title: "2D Layouting", lifecycleStage: "DESIGN", module: "INTERIORS" },
  { category: "Interior", title: "3D & Render", lifecycleStage: "DESIGN", module: "INTERIORS" },
  { category: "Interior", title: "Elevations", lifecycleStage: "DESIGN", module: "INTERIORS" },
  { category: "Interior", title: "Interior BOQs & Ordering", lifecycleStage: "DESIGN", module: "INTERIORS" },
  { category: "Interior", title: "Material Procurement", lifecycleStage: "DESIGN", module: "INTERIORS" },
  { category: "Interior", title: "Documentation & Handover", lifecycleStage: "DESIGN", module: "INTERIORS" },
  { category: "Plain and Reinforced Cement Concrete", title: "Providing and laying in position cement concrete of specified grade excluding the cost of centering and shuttering", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Plain and Reinforced Cement Concrete", title: "1:2:4 (1 cement : 2 coarse sand (zone-III) : 4 graded stone aggregate 20 mm nominal size)", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Plain and Reinforced Cement Concrete", title: "Reinforced cement concrete work in walls (any thickness), including attached pilasters, buttresses, plinth and string courses, fillets, columns, pillars, piers, abutments, posts and struts etc. above plinth level up to floor five level, excluding cost of centering, shuttering, finishing and reinforcement :", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Plain and Reinforced Cement Concrete", title: "1:1.5:3 (1 cement : 1.5 coarse sand(zone-III) : 3 graded stone aggregate 20 mm nominal size)", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Plain and Reinforced Cement Concrete", title: "FORM WORK", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Plain and Reinforced Cement Concrete", title: "Centering and shuttering including strutting, propping etc. and removal of form for :", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Plain and Reinforced Cement Concrete", title: "Lintels, beams, plinth beams, girders, bressumers and cantilevers", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Plain and Reinforced Cement Concrete", title: "Columns, Pillars, Piers, Abutments, Posts and Struts", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Plain and Reinforced Cement Concrete", title: "CORE Cutting as per design if any", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Masonry Work", title: "Providing and laying autoclaved aerated cement blocks masonry with 150mm/230mm/300 mm thick AAC blocks in super structure above plinth level up to floor V level with RCC band at sill level and lintel level with approved block laying polymer modified adhesive mortar all complete as per direction of Engineer-in-Charge.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Water Proofing work", title: "Toilet,kitchen and Bar Area  waterproofing (Sunken) :-All surface area should cleaned up to visible of hair cracks / aggregate texture. Cleaning of RCC member should be done by hacking tool, wire brush, wire grinder & air blower etc. Open cracks & construction joints should be sealed with cement mortar with additive Conplast WL / Cebex 100 / repair mortar or equivalent as per manufacturers specification etc complete. All clean & treated area should tested for water tighness by flooding water. All wet spots & water leakage area should mark for treatment. Providing and applying primer in one coat at coverage of 6-7 Sqm per Ltr using brush or long nap roller prior to application. Allow the surface to dry completely. Providing and applying single / two component WPM 002 / Blueguard / Revestidan @2.2 kgs / sqm in two coats by Design Engineer, advanced acrylic cementitious modified, fast drying, tough, uniquely formulated with synthetic micro fibers to increase its strength, applying first coat of WPM 002 / Blueguard / Revestidan, sandwiching Deck Web / Chopstrand mat on wet first coat at internal and external corners, allowing it to dry completely, after 4 Hrs time gap, applying second coat of WPM 002 / Blueguard / Revestidan in perpendicular direction to the applied first coat and allowing it to dry completely, etc and complete as per manufacturer's specification. [The membrane shall confirm to:-Elongation at Break : > 150 %; Tensile Strength : > 1 MPa; Water Absorption : 4.3%; Shore A hardness - > 80]", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Water Proofing work", title: "Regular Waterproofing as per location of the mall and brand", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "MS Framing", title: "MS Frame work for wall if needed", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "MS Framing", title: "Bar Fabrication", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "MS Framing", title: "Wall designs with MS Framing if any", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "MS Framing", title: "Outside Cabana's MS Framing Structures if any", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "MS Framing", title: "Wall Partioning if needed MS Framing", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "MS Framing", title: "Façade designs if MS framing needed", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "MS Framing", title: "Ceiling Designs MS if needed", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "MS Framing", title: "Staircase work if needed", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "MS Framing", title: "Mezzanine work if ms structure involved", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "MS Framing", title: "Outside board hanging if MS work involved", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "MS Framing", title: "MS Structures involved in design part including music light tv", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "MS Framing", title: "Providing and fixing planters with using MS framing", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Tiling", title: "P/f  Grey Matt Tile, in Kitchen floor with drain cutting.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Tiling", title: "As above, 4\" skirting in grey matt tile  in Kitchen.\\", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Tiling", title: "P/f  White commercial Tile (18\" x 12\") wall cladding in the kitchen area till full height and inner side of bar till 3'-6\".", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Tiling", title: "P/f  White commercial Tile (18\" x 12\") flooring in the liquor and dry store.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Tiling", title: "Providing and fixing chrome finish strip between different colour  terrazzo flooring, size-25x8mm", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Tiling", title: "Providing and fixing of different colour terrazzo/Top End approved tile cast in situ as per the shade or approved Sample with grinding and Polishing complete work .", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Tiling", title: "As above, 2\" skirting in Terrazzo, 20-25MM Thick in dining area.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Tiling", title: "Fixing Customized tiles of size 600 x 600mm on bar and elevated flooring in color as per selection with matching pigment grouting, complete as per dwg.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Tiling", title: "Fixing Grey floor tiles of size 800 x 2400x15mm onInside Bar area  as per selection with matching pigment grouting, complete as per dwg.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Tiling", title: "Fixing Floor tiles of size 100 x 100mm on toilet  floor of colour as per selection with matching pigment grouting, complete as per dwg.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Tiling", title: "Fixing  Wall tiles of size 100 x 100mm Tile wall cladding Tilet wall of colour as per selection with matching pigment grouting, complete as per dwg.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Tiling", title: "Providing and fixing 50mm thick greynite stone on bar back on 20mm thick ply-board,using adhesive on top ,chamfering if any, with stone polishing as required.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Tiling", title: "Providing and fixing 50mm thick white quartz or as per design on counter tops cast over 20mm thick cement mortar 1:4 (1 cement:4 coarse sand) mix, including  cutting of   stone,cement slurry stained with matching pigment,chamfering if any, with stone polishing as required.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Tiling", title: "P/f granite stone chamfering.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Tiling", title: "Granite Flooring work if any", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Tiling", title: "Fountain Granite Stone if any", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Tiling", title: "Terrance Flooring as per design", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "POP and Gypsum", title: "Providing and applying POP false Ceiling up to 20-25mm thick or wherever specified to prepare the surface even and smooth including all leads and lifts, Item includes G.I. Perimeter Channels of size 0.55mm thick (having One Flange of 20mm and another flange of 30mm and a web of 27mm) along with perimeter of ceiling, screw fixed to brick wall / partition with the help of Nylon sleeves and screws at750mm centers. Then suspending G.I. intermediate channels of size 45mm (0.9mm thick with two flanges of 15mm each)  from the soffit at 1000mm centers with ceiling angle of width 25mm X 10mm X 0.55mm thick fixed to soffit with G.I. cleat and steel expansion fasteners. Ceiling section of 0.55mm thick having knurled web of 51.5mm and two flanges of 26mm each with lips of 10.5mm are then fixed to the intermediate channel with the help of connecting clips and in direction perpendicular to the intermediate channel at 457 mm centers.   POP facia of 150 mm high as per the direction of the Architect.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "POP and Gypsum", title: "POP Stepped False Ceiling - Including Making all kind of Coves,  Accessories, Designs as per drawings", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "POP and Gypsum", title: "POP flat False Ceiling - Including Making all kind of Coves,  Accessories, Designs as per drawings", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "POP and Gypsum", title: "Providing  and  fixing 10mm Thk POP wall punning work", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Plumbing", title: "Complete Kitchen drain lines", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Plumbing", title: "Kitchen PVC Pipe fittings and water tanks if needed", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Plumbing", title: "Water Floor Drain with PVC Pipe Fittings", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Plumbing", title: "Water Hot and Cold connections over Washup area and burners", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Plumbing", title: "Bar Area water lines and Sewage connections", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Plumbing", title: "Floor PVC lines from Bar area to main drain", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Plumbing", title: "AC Water drain if needed", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Plumbing", title: "Dishwasher Connections", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Plumbing", title: "Supply", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "Providing and fixing of all Waterproof electrical points in OUTDOOR OPEN area, as per Electrical layout, Inclusive of fixing/laying of conduits, boxes and wires.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "Boxes & Conduits  :  Any Standard make", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "Switch and socket : LEGRAND /NORTH WEST   Wire : HAVELS", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "Providing and laying of Electrical fixtures as per electrical layout", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "Providing and fixing of AC points as per drawing and laying of wiring and piping as per AC vendor requirement and detail", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "Switch Board", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "Switches", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "5 AMP points", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "15AMP points", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "Data Points", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "Telephone Points", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "Chandeliers Point", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "Wall lights Points", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "CCTV wiring", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "Excluding main panels,music wiring, HVAC power cables/switches.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "P/F 240 Amp Main Electriac panel as per SLD drawing and details", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "Distribution Board", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "8 WAY TPN ( For Normal Supply)", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "Incomer", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "1 No. 63A, 4P MCB + 3x40A / 30mA DP ELCB's + separate neutral link per phase", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "Outgoing", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "18 Nos. 6A/10A/16A/20/25A SP MCB's", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "L+PDB- 8WAY TPN DB as described above", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "12 WAY TPN ( For Normal Supply)", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "L+PDB- 12WAY TPN DB as described above", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "P/F 12 Way DP DB Box 32A ELCB 1 Nos. 16A MCB SP 10 No", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "P/F 1KW Inverter with Dry Battery with MS Sand", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "P & F Light point 2.5mm (Finolex / Havel's / plycap)", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "P & F Light point 2.5mm - Looping  (Finolex / Havel's / plycap)", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "P & F Light Modular plug point 5-A Roma 2.5mm Wire", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "P & F Light Modular plug point 5-A Roma 2.5mm (Looping)", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "P & F Power point 15-A Roma 4mm (Finolex / Havel's)", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "P & F Power point 15-A Roma 4mm (Finolex / Havel's) Looping", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "P&F Indistrial point 32A 4mm 2core, 1.5mm 1core indistrial box SPMCB 1nos (havels/ancor)", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "DB to switch board 2.5mm 2core 1.5mm 1core with m/s box (Havels policab) or Signage", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "P & F 1.5mm 2 core lead", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "P & F 2.5mm 2 core lead", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "THREE PHESE 4X4C AR,HU,EXZUST", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "P & F PVC FRLS Coundute 1\" bundle", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "P&F M/S fexible pipe", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "P&F 20mm faxible pipe", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "P&F Cat-6, D-link point networking, CCTV, WiFi, projector point", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "Speaker Point, 1.5mm 2core", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "Data face plate with io", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "Light fitting (labour charge)", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "P&F Kitchen tube lights", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "P&F Tv point RJ 45 cable with M/S Box", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "P&F T-5 Tube", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "P&F Light conector 10A", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Electical", title: "P&F Gi Earthing wire 8 SWG", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Ducting", title: "GI Ducting for Air Washer and Air Exhaust system.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Ducting", title: "Gauge  26, Dia 15*18 inch, Running Length 8*3", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Ducting", title: "Air Washer as per size CFM and Motor make", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Ducting", title: "Air Scrubber as per size CFM and Motor Make", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Ducting", title: "Exhaust as per size and CFM and Motor Make", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Ducting", title: "Grills for Air Washer", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Ducting", title: "SS Hood 16 gauge 302 no", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Ducting", title: "SS Filters for the hood", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Ducting", title: "Light provision for the hood", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Ducting", title: "oil container and hooks for hanging", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Ducting", title: "MS Stand for Machine Hanging", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Fire Work", title: "Supply Installation of Sprinkler with all piping as required", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Fire Work", title: "Additional sprinkler point in Bar Area asper Mall Management Requirment", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Fire Work", title: "Supply installation of conventonal Smoke detector with all wiring condute as required", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Fire Work", title: "Supply installation of conventonal Heat detector in kitchen with all wiring condute as required", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Fire Work", title: "Supply installation of RI", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Fire Work", title: "Supply installation of MCP", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Fire Work", title: "Supply Installation of Hotter", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Fire Work", title: "Supply installation of 2 Zone fire alarm panel", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Fire Work", title: "Controle module for integration of BMS", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Fire Work", title: "Flash type hotter", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Fire Work", title: "Integration of AC and Exust Duct", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Fire Work", title: "Exaust Dust Sprinkler", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Fire Work", title: "Exit Signage UPS", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Fire Work", title: "Panel Battery", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Installation, Testing & commissioning Charges including lifting & shifting of  following  AHUs The installation shall be complete with nut washer fastner threading rods with mounting on spring isolators", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "TBA CFM AHU", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "TBA CFM HVAC", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "TBA CFM DX", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "PVC Drain Pipe", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "PVC piping with fittings & supprots etc duly insulated with class 6 mm Nitrile foam of  complete as per specifictaion", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "32 mm(MAKE - SUPREME/POLYPACK/PRINCE)", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Chilled Water Piping", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Supply, Installation, testing & commissioning of  following sizes of 'C' CLASS chilled water pipe  inside the building with necessary clamps, fitting etc. adequately anchored to rigid supports and duly insulated with NITRILE RUBBER SHEET INSULATION Class 1 of as required and as per design.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "50 mm dia (Make -JINDAL) Insulation - 25 mm", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "40 mm dia (Make -JINDAL) Insulation - 25 mm", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Supply,  Installation,  testing  &  commissioning  of   following  sizes  of  valves,  strainers,  gauge,   etc.  in chilled water piping duly insulated complete with fitting, flanges etc. as per the same specifications", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Butterfly Valves- Zoloto/Castle", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "50 mm dia", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Ball Valves For Drain Castle Make", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "15 mm dia", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Y-Strainer - Sant/Emerald", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Auto Air Purging Castle Make", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "10 mm", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "2-Way Motorised Valves Complete With Motor, Actuator, Transformer, Thermostat etc. (Make -\nHoneywell/Siemens)", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "40 mm", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Thermometer Make -H Guru", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Pressure Gauges 100mm Dial with Ball Valve, Syphon Make -H Guru", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "AHU Panel", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "AIR DISTRIBUTIONS:", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Ducting", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Supply,  Installation  and  Testing  of  Site  fabricated  GSS   rectangular  ducting   complete  with  gaskets hanging arrangement including fully threaded GI  rods ,Hangers & Supports complete with end fixing  in accordance with the\napproved shop  drawings and specifications.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "24 Guage Factory Fabricacted Rectangular GSS (MAKE -SAIL/JINDAL/TATA BHUSHAN (TSB)/ESSAR)", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "22G Guage Factory Fabricacted Rectangular GSS", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "22 Gauge Flat Oval Ducting", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Acoustic Lining", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Supply   and   Application  of   internal   acoustic lining open cell nitrile rubber for sound dampening with density of\n140-180kg/m3", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "10 mm Thick open cell nitrile accoustic", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Thermal Insulation of Duct", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Supply and Application of external thermal insulation of 9mm thick using closed cell elastomeric nitrile rubber Insulation of following thickness. AC duct in exposed ceiling areas will have to be done internally.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Canvas Connection", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Supply,  Installation,  Testing  of  antivibration  neoprene  coated  flexible  joints  at  the  outlet  of  AHUs. Flexible connections  shall be constructed using  fire retardant  fabric with frame/flange on both sides.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Linear Grill", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Supply,  Installation,  Testing  and  Balancing  of  linear supply  cum  return  air  grilles  complete  with  fixed core as per approved shop drawings and specifications. The grilles shall be of approved  colour & shade.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Powder coated  aluminium  grilles  of  extruded   sections  with  integral  flanges  on both  sides &  ends as required\ncomplete with corner pieces.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "100/150/200/250 mm High grilles (MAKE - Cynor)", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Curved Grill for Oval Ducting", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Circular Diffuser - 200 mm DIA", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Box Type Damper", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "For Rectangular Ducts Supply,  Installation  and  Testing  of   20 Gauge GI box type volume control\ndampers as per the specifications and shop drawings.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Collar Damper (Make Cynor)", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Supply,  Installation and Testing  of  Extruded Aluminium  multi blade type    louver  dampers  as   per the specifications and shop drawings.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "AC Work", title: "Freight/scaffolding/lifting shifting charge", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Carpentor", title: "Wall Panelling and wall wood work with HDMR green approved ply", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Carpentor", title: "Bar designs and wall wooden work as per approved 3D and designs", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Carpentor", title: "(a)\tApplying anti-termite and anti- borer paint to wooden frame work wherever directed\n(b)\t Applying three or more coats of melamine polish /painting of approved quality and shade to have desired, finish to all exposed surface of teak wood members beadings, board etc. including preparing of surface by sand papering, applying putty etc. complete", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Carpentor", title: "Providing and fixing wooden dj counter using Counter wooden batten  with 12mm Thk ply pasting on  Counter top 19mm ply fixing with laminate finish.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Carpentor", title: "Providing  and  fixing  Wooden Trap door 1300 X 2200mm with Laminate finish use 18 mm ply with all necessary SS hardware and fittings. L n Key  etc.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Carpentor", title: "Providing  and  fixing door frames of size (2'-9\"x8'-0\") as per drawing with all the fittings and hardware", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Carpentor", title: "Providing  and  fixing both side laminate door shutters of size (2'-9\"x8'-0\") as per drawing with all the fittings and hardware", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Carpentor", title: "Service Stations as per designs and 3d model", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Carpentor", title: "Podium as per designs", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Carpentor", title: "Complete Wall Designs as per 3d model", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Carpentor", title: "Kitchen Doors , Washroom doors as per design", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Carpentor", title: "Bar Terrace designs", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Carpentor", title: "Ceiling Pannelling If any", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Carpentor", title: "Bar Hanging if any", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Paint", title: "Providing and fixing in position rough textured ceiling as per design and drawing.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Paint", title: "WALL PAINT Premium apcolite emulsion - Painting the walls including surface preparation, primer, putty with 2 coats of best quality APCOLITE  emulsion paint complete in desired shades and colours. Brand : Apcolite Premium by Asian/British/Nerolac/Nipon.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Paint", title: "Providing  and fixing Texture paint with proper base Interanal and extarnal wall.(Asian /Berger)", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Paint", title: "Providing and applyin Ceiling paint two coat Birla putty for making proper base  with plastic  emulsion  paint (Asian premium)", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Paint", title: "Painting with base satin enamel  paint (Asian /Berger)", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Paint", title: "Brand : Apcolite Premium by Asian/British/Nerolac/Nipon.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Paint", title: "Texture Designs as per 3d", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Paint", title: "Enamal Paints as per design", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Paint", title: "Outside terrance or façade paint as per design", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Paint", title: "Façade design if paint is an elemant", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Music", title: "Audio Interconnect Cables", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Music", title: "Speaker Cable-\n2 core , 1.5mm ,Silver speaker cable - 100M,OFC copper", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Music", title: "Installation, Testing & Commissioning charges", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Light and Design", title: "Spare Parts", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Light and Design", title: "Wiring", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Light and Design", title: "Installations", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Light and Design", title: "Wall Lamps as per designs", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Light and Design", title: "Chandeliers as per designs", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Light and Design", title: "Ceiling surface lights as per designs", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Light and Design", title: "Tracks lights and panels lights", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Light and Design", title: "Complete Neon work and profile lights if needed as per designs", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Gas", title: "MS ERW C CLASS PIPE 1.5\"", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Gas", title: "MS BEND 1.5\"", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Gas", title: "END CAP 1.5\"", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Gas", title: "BALL VALVE 1.5\"", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Gas", title: "BALL VALVE half-inch\" POINT", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Gas", title: "PRESSURE GAUGE (4\")", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Gas", title: "ANGLE SUPPORT WHIT U CLAMPE", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Gas", title: "INSTALLATION CHARGES (INC. PAINT, TESTING, COMISSIONING) AND\nDISMENTLING CHARGES", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Gas", title: "THIRD PARTY INSPECTION", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Gas", title: "SAB METAR", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Gas", title: "REGULETOR", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Gas", title: "FILTAR", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Gas", title: "SITC of Kitchen Suppression System Cylinder with all fittings.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Designs and Décor", title: "Wall Panels", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Designs and Décor", title: "Wall Papers", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Designs and Décor", title: "Neon Lights", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Designs and Décor", title: "inside brand logos", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Designs and Décor", title: "Artificial Flowers", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Designs and Décor", title: "Wall Art", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Designs and Décor", title: "Tree Art", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Designs and Décor", title: "Acrylic Panels - Rose Gold", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Designs and Décor", title: "Fountains", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Designs and Décor", title: "Grass Flooring", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Designs and Décor", title: "PVC Dados", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Designs and Décor", title: "Swings/Zoca Circle", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Designs and Décor", title: "Bar Counters", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Designs and Décor", title: "wallpaper/graffti", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Designs and Décor", title: "Premium Roof Designs", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Designs and Décor", title: "wall light panels", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Designs and Décor", title: "Louvers", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Designs and Décor", title: "Ripple Sheets", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Designs and Décor", title: "PVC Panels", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Designs and Décor", title: "CNC Designs", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Designs and Décor", title: "ACP Sheet CNC designs", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Furniture", title: "Seats - All the seating arrangement interior and exterior will be based on designs approved once.\nTables - They will be in mixed wood (for standard size 30inches x 48inches) in market price and laminates in matt and gloss as per designs approved.\nTables - different sizes (2ft x 2ft, 2ft 6inches x 3ft, 2ft x 5 ft) with industrial base of iron and table top in pine wood or meranti wood (front thickness of 2inches).", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Furniture", title: "SOFA -Foam of Kurlon brand or equivalent ; Understructure in Hardwood of Merandi or chaap. Fabric quilting & Piping as per design provided. Exposed legs of sofa to be Teakwoodi/ Fabric as per selection,", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Furniture", title: "DINING CHAIRS - High height chairs with arms & teak wood legs. Seat size -18 inches width. Seat and back to be upholstered with quilting patterns; Foam of Kurlon brand or equivalent;", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Furniture", title: "Tables - Commercial board with Powdercoated M.S. understruture & legs, matt polish or paint finish of desired shade & colour.", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Furniture", title: "Service and Outdoor Console - Understructure in 18mm thick HDHMR board by Bhutan tuff or equivalent, Matt/Hi gloss paint in desired shade.( Moved to next stage with current budget)", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Furniture", title: "Entrance podium in 18mm thick HDHMR board by Bhutan tuff or equivalent, Matt/hi-gloss paint in desired shade. ( Moved to next stage with current budget)", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Furniture", title: "Cartage for furniture", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Glass Work", title: "Rose Gold/Copper Normal Glass Work", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Glass Work", title: "Tuffon Door and Windows", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Glass Work", title: "Designs of Normal Glass as per 3d", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Glass Work", title: "Bar Tuffon glass for racks", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Board Work", title: "Brand Board with acp work", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Board Work", title: "Logos as per 3d", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Board Work", title: "Branding and Neon as per 3d", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Board Work", title: "ACP work as per 3d", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Board Work", title: "Acrylic work as per 3D", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Plant Work", title: "Real Plant List", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Plant Work", title: "Artificial Planters", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "LED Screens 42/50/65", title: "LED Screens 42/50/65", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Integrations", title: "Fire supression", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Integrations", title: "Fire Mall Integration", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Integrations", title: "Hood Integration", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "Integrations", title: "AC integrations", lifecycleStage: "CONSTRUCTION_EXECUTION", module: "PROJECTS" },
  { category: "OPERATION", title: "L.O.I creation and sigining", lifecycleStage: "LEGAL_COMPLIANCE", module: "LEGAL" },
  { category: "OPERATION", title: "Agreement Creation and Signing", lifecycleStage: "LEGAL_COMPLIANCE", module: "LEGAL" },
  { category: "OPERATION", title: "Royalty & Service Fee Bill Genration", lifecycleStage: "POST_OPENING", module: "OPERATIONS" },
  { category: "OPERATION", title: "Royality & Service Fee Follow-up Calls & Emails", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "OPERATION", title: "Welcome Letter", lifecycleStage: "PROJECT_HANDOVER", module: "PROJECTS" },
  { category: "OPERATION", title: "Induction Scheduling", lifecycleStage: "PROJECT_HANDOVER", module: "PROJECTS" },
  { category: "OPERATION", title: "Master File Creation", lifecycleStage: "PROJECT_HANDOVER", module: "PROJECTS" },
  { category: "OPERATION", title: "Documnetation Updation (owners)", lifecycleStage: "PROJECT_HANDOVER", module: "PROJECTS" },
  { category: "OPERATION", title: "Master File Updation", lifecycleStage: "PROJECT_HANDOVER", module: "PROJECTS" },
  { category: "OPERATION", title: "Uniform Ordering and maintaining", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "OPERATION", title: "PDC & Agreement Follow-ups", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "OPERATION", title: "Customer Complaint Training", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "OPERATION", title: "Royalty Follow-ups", lifecycleStage: "POST_OPENING", module: "OPERATIONS" },
  { category: "OPERATION", title: "Customer Complaint Tracking and Follow-up meetings", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "OPERATION", title: "Store Order training and tracking", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "OPERATION", title: "Agreement Signing Confirmation Mail", lifecycleStage: "LEGAL_COMPLIANCE", module: "LEGAL" },
  { category: "OPERATION", title: "1st Site Visit (15 days out)", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "OPERATION", title: "2nd Site Visit (8 days out)", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "OPERATION", title: "3rd Site Visit (3 days out)", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "OPERATION", title: "Pan Card Details & copy", lifecycleStage: "LEGAL_COMPLIANCE", module: "LEGAL" },
  { category: "OPERATION", title: "Current A/c Deatails & cancelled Cheque", lifecycleStage: "LEGAL_COMPLIANCE", module: "LEGAL" },
  { category: "OPERATION", title: "Gst Details & Copy", lifecycleStage: "LEGAL_COMPLIANCE", module: "LEGAL" },
  { category: "OPERATION", title: "FSSAI application (state)", lifecycleStage: "LICENSING", module: "LEGAL" },
  { category: "OPERATION", title: "FSSAI application (Hawker)", lifecycleStage: "LICENSING", module: "LEGAL" },
  { category: "OPERATION", title: "FSSAI received", lifecycleStage: "LICENSING", module: "LEGAL" },
  { category: "OPERATION", title: "Zomato Delivery", lifecycleStage: "TECHNOLOGY_DEPLOYMENT", module: "OPERATIONS" },
  { category: "OPERATION", title: "Zomato Dining", lifecycleStage: "TECHNOLOGY_DEPLOYMENT", module: "OPERATIONS" },
  { category: "OPERATION", title: "Swiggy Dineout", lifecycleStage: "TECHNOLOGY_DEPLOYMENT", module: "OPERATIONS" },
  { category: "OPERATION", title: "Swiggy Delivery", lifecycleStage: "TECHNOLOGY_DEPLOYMENT", module: "OPERATIONS" },
  { category: "OPERATION", title: "Hyperpure setup", lifecycleStage: "TECHNOLOGY_DEPLOYMENT", module: "OPERATIONS" },
  { category: "OPERATION", title: "Eazy Diner Setup", lifecycleStage: "TECHNOLOGY_DEPLOYMENT", module: "OPERATIONS" },
  { category: "OPERATION", title: "Petpooja ID setup", lifecycleStage: "TECHNOLOGY_DEPLOYMENT", module: "OPERATIONS" },
  { category: "OPERATION", title: "POS instalation", lifecycleStage: "TECHNOLOGY_DEPLOYMENT", module: "OPERATIONS" },
  { category: "OPERATION", title: "POS setup", lifecycleStage: "TECHNOLOGY_DEPLOYMENT", module: "OPERATIONS" },
  { category: "OPERATION", title: "Outlet Certificate", lifecycleStage: "LICENSING", module: "LEGAL" },
  { category: "OPERATION", title: "Black Box", lifecycleStage: "TECHNOLOGY_DEPLOYMENT", module: "OPERATIONS" },
  { category: "OPERATION", title: "Service Staff Training", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "OPERATION", title: "Menu Proofreading", lifecycleStage: "TECHNOLOGY_DEPLOYMENT", module: "OPERATIONS" },
  { category: "OPERATION", title: "Menu Qr Code", lifecycleStage: "TECHNOLOGY_DEPLOYMENT", module: "OPERATIONS" },
  { category: "OPERATION", title: "Menu training", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "OPERATION", title: "Site Updates", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "OPERATION", title: "Equipment Recived confirmation", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "OPERATION", title: "Furniture Recived Confirmation", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "OPERATION", title: "Site Visit as Needed", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "OPERATION", title: "FSSAI Training", lifecycleStage: "LICENSING", module: "LEGAL" },
  { category: "OPERATION", title: "POS Training", lifecycleStage: "TECHNOLOGY_DEPLOYMENT", module: "OPERATIONS" },
  { category: "OPERATION", title: "Construction Followups", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "OPERATION", title: "Problrm Troubleshooting", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "OPERATION", title: "Employee Recognition Program", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "OPERATION", title: "Store Recognition Program", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "OPERATION", title: "Sales Monitoring", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "OPERATION", title: "Purchase Monitering", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "OPERATION", title: "HR Support", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "OPERATION", title: "Marketing support", lifecycleStage: "PRE_LAUNCH_MARKETING", module: "MARKETING" },
  { category: "OPERATION", title: "Service Staff Screening", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "OPERATION", title: "Staffing Consultancy Management", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "OPERATION", title: "Marketing Offer Creation", lifecycleStage: "PRE_LAUNCH_MARKETING", module: "MARKETING" },
  { category: "OPERATION", title: "Outlet Documnetation", lifecycleStage: "PROJECT_HANDOVER", module: "PROJECTS" },
  { category: "OPERATION", title: "Market Research and Analysis", lifecycleStage: "LOCATION_ACQUISITION", module: "PROPERTY" },
  { category: "CULINARY", title: "Kitchen Layout & Design", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Menu Devlopment", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Equipment & Supplies", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Staff interviews & Trials", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Training & Orientation", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Soft Opening Preperations", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Final Prepration (Kitchen setup)", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Foods Trials", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Quality Control & Assurence", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Staff Training & Devlopment", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Training Calander", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Recipies S.O.Ps", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Vendor Management (Kitchen & Food)", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Marketing Promotion Offers", lifecycleStage: "PRE_LAUNCH_MARKETING", module: "MARKETING" },
  { category: "CULINARY", title: "Training Recorde Maintainence", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "WORK TABLE WITH UNDER AND MIDDLE SHELF", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "4 BURNER CONTI RANGE", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "CONTINENTAL OVEN", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "3 BURNER INDIAN RANGE", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "WALK IN CHILLER", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "DOGH PROFER", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "BACK BAR CHILLER TRUEFROST", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "DOUGH MACHINE", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "WOOD FIRE OVEN", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "BAR TABLE", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "WORKING TABLE UNDER COUNTER", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "DOUBLE OVERHEAD SHELF", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "ELECTRIC OVEN WITH STAND", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "GRILLER PLATE", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "DOUBLE TANK FRYER 6+6 LTR", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "andrew james BLENDER", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "2 DOOR UNDER COUNTER REF WITH GN PAN FOR TOP 1/6 GN PAN 8 NOS", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "DOUBLE SINK UNIT", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "DOUBLE OVER HEAD SHELF", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "DEEP FREZZER ( VOLATS", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "GEYSER", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "RO", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "SINGLE SINK UNIT", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "CHEF PICKUP TABLE WITH HEATING FILAMENT", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "UTENSILS RACK", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "A P Spoon", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "A P Fork", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "A P Knife", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Tea Spoon", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Reserved Sign", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Service Spoon", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Cheese Knife", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Service Fork", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Steak Knife", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Soup Spoon", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Chilly oil dispenser", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Olive oil dispenser", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Balsamic vinegar dispenser", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Oregano Dispenser", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Chilly Flake Dispenser", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Paper Mats", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Branded Paper napkins small", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Branded Paper napkins big", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Reserved Tag", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "No smoking Tag Big", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Dry day Tag", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Bill Folder", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Kot and Bot pads", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "TABLE CADY *", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "SALT AND PEPPER", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "SS MASALA BOX WITH LID (6 COMPARTMENTS)", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Pressure Cooker (10 ltr) HAWKIN", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "S S Mixing Bowls 7'", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "S S MIXING BOWL 5'", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Katories", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Wire Whisk balloon small 7 '", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Wire Whisk Balloon medium size 9 '", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Sauce Pan IMPORTED 5 LT", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "SAUCE PAN IMPORTED 10 LT", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "S S Conical Strainer MEDIUM", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "SS CONICAL STRAINER LARGE", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "SS Multi Purpose Tong 12'  KITCHEN", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Pasta Strainer", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "MS Grater with Leg INDIAN", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "SS Soup Laddle", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "SS Portioning Laddle", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "SS Chinese Laddle with wooden Handle", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Ice Cream ScoopeR", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "SS Stock Pot with handle 15 ltr", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "SS PAN FABRICATED 8'", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "SS  PAN FABRICATED 6'", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "SS  PAN FABRICATED 10'", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Gas Lighter long handle", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Sharpening Stone JAPANESE", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Bread Knive", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Non stick Pan -6' ( futura, telflon coated)", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "PIZZA CUTTER (Remington)", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "SS Steak Spatula", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Plastic & SS Funnel", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Wooden Lemon Squeezer", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Pasta Machine MANUAL", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Pallete Knive platting", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "S.S Tray", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Portable Hand Blender", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Vegetable Crates For Vegetable jaali", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Rolling Pin", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Electric Mixie, blender, food processor- Sujata, Inalsa", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Electical Microwave 15 Ltrs", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "GN PAN 1/4 only lid", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "GN PAN 1/1 200 mm", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "GN PAN 1/2  with lid 150mm", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "GN PAN 1/9 100 mm with lid", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "GN PAN 1/2 with lid 150 MM", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "GN PAN 1/3", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "G/N PAN WITH HOLES", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Grill Brush small", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Bone Plucker / Tweezer", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "SS Spatula with groves wooden handle", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Colander/ Rice Strainer BIG", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Lettuce Dryer plastice SMALL", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Pan stands small ( check size)", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Pizza Board wooden FOR CUTTING", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Steel tray ( 15 x 15x12)", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Sizzle Plates 10' round", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Tempura strainer, fine wire mesh", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Wooden Spatula", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Steel Jhara", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Table Squeeze MEDIUM", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Wooden handle scraper", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Paper Roll stand", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Cling Wrap Stand", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Terrine Mould", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Turning Slicer", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Grater with handle", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Small Karai Iron 12'", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Peeler, Y SHAPE", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Measuring Jug 1000ml", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Measuring CUP  BIG SET", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Silp Mat(bakery)", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Kitchen scissor", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Basting Brush , nylon wooden handle, 6 '", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "SS Funnel", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Squeeze Bottles small", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Squeeze Bottles big", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Nozzle Set", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Pocket Kitchen Thermometer", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Plastic Pipping bag (1X250)", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Airtight container medium size 500 ml", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Kitchen Spoons", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Weighing Scale electric FOR GMS", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "S.S Storage bin rice", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "BAMBOO BRUSH", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "STAF PLATES", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Staff Spoons", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Staff Glasses", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Staff Service laddle", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Food Grade Plastic Container with lids 500gms", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "SS Fabricated Patila 10 ltrs/ Hindolium Pailas", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Knive Magnetic Strip", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Plastic Hand Gloves", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Aluminum Patila DIFFERENT SIZE SETS", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Green chopping board", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "White chopping board", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Red chopping board", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Blue chopping board", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Storage bin Maida + Atta CAMBRO", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Round cutters", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Condiment tray", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "Square ice cream keeper", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "CULINARY", title: "MICROWAVE", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "MARKETING", title: "Branding Setup", lifecycleStage: "PRE_LAUNCH_MARKETING", module: "MARKETING" },
  { category: "MARKETING", title: "Franchise Onboarding", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "MARKETING", title: "Online Media Setup", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "MARKETING", title: "GMB Profile Setup", lifecycleStage: "PRE_LAUNCH_MARKETING", module: "MARKETING" },
  { category: "MARKETING", title: "Official Outlet Mail Id Setup", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "MARKETING", title: "Outdoor Signage", lifecycleStage: "PRE_LAUNCH_MARKETING", module: "MARKETING" },
  { category: "MARKETING", title: "Strategy & Planning", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "MARKETING", title: "Budget Allocation (Internal)", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "MARKETING", title: "Optmized Profiles", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "MARKETING", title: "Digital Ads Design", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "MARKETING", title: "In-Store Collateral", lifecycleStage: "PRE_LAUNCH_MARKETING", module: "MARKETING" },
  { category: "MARKETING", title: "Brand Merchandise", lifecycleStage: "PRE_LAUNCH_MARKETING", module: "MARKETING" },
  { category: "MARKETING", title: "Pre-Launch Social Media Content", lifecycleStage: "PRE_LAUNCH_MARKETING", module: "MARKETING" },
  { category: "MARKETING", title: "Limited-Time Offers", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "MARKETING", title: "Video Content", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "MARKETING", title: "Marketing Collaboration", lifecycleStage: "PRE_LAUNCH_MARKETING", module: "MARKETING" },
  { category: "MARKETING", title: "Social Media Posts", lifecycleStage: "PRE_LAUNCH_MARKETING", module: "MARKETING" },
  { category: "MARKETING", title: "Digital & Physical Menus", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "MARKETING", title: "Party Menu & Special Menus", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "MARKETING", title: "Marketing Support Group", lifecycleStage: "PRE_LAUNCH_MARKETING", module: "MARKETING" },
  { category: "MARKETING", title: "QR Code Generation", lifecycleStage: "TECHNOLOGY_DEPLOYMENT", module: "OPERATIONS" },
  { category: "MARKETING", title: "Online Ads", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "MARKETING", title: "Whtsapp Marketing", lifecycleStage: "PRE_LAUNCH_MARKETING", module: "MARKETING" },
  { category: "MARKETING", title: "Press Releases", lifecycleStage: "PRE_LAUNCH_MARKETING", module: "MARKETING" },
  { category: "MARKETING", title: "Influencer Collaborations", lifecycleStage: "PRE_LAUNCH_MARKETING", module: "MARKETING" },
  { category: "MARKETING", title: "Community Engagement", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "MARKETING", title: "Grand Opening", lifecycleStage: "GRAND_LAUNCH", module: "MARKETING" },
  { category: "MARKETING", title: "Influencers, Media Invite", lifecycleStage: "PRE_LAUNCH_MARKETING", module: "MARKETING" },
  { category: "MARKETING", title: "Photography & Video Coverages", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "MARKETING", title: "Launch Day Content", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "MARKETING", title: "Reputation Management", lifecycleStage: "POST_OPENING", module: "OPERATIONS" },
  { category: "MARKETING", title: "Local SEO", lifecycleStage: "PRE_LAUNCH_MARKETING", module: "MARKETING" },
  { category: "MARKETING", title: "Franchise Connect After Opening", lifecycleStage: "POST_OPENING", module: "OPERATIONS" },
  { category: "MARKETING", title: "Local Partnerships Guidance", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "MARKETING", title: "SEO Optimization", lifecycleStage: "PRE_LAUNCH_MARKETING", module: "MARKETING" },
  { category: "MARKETING", title: "Online Reservation System", lifecycleStage: "PRE_LAUNCH_MARKETING", module: "MARKETING" },
  { category: "MARKETING", title: "On-Page SEO", lifecycleStage: "PRE_LAUNCH_MARKETING", module: "MARKETING" },
  { category: "MARKETING", title: "Content SEO", lifecycleStage: "PRE_LAUNCH_MARKETING", module: "MARKETING" },
  { category: "MARKETING", title: "Order Management", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "HR", title: "Owner Induction", lifecycleStage: "PROJECT_HANDOVER", module: "PROJECTS" },
  { category: "HR", title: "All Site Staff Planning & Budgeting", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "HR", title: "HR Overview", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "HR", title: "Staffing Process (new opening and pending tickets)", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "HR", title: "Staff Induction Process", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "HR", title: "Offer Letters & Appointment", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "HR", title: "Staffing as Required (Tickets)", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "HR", title: "Franchise Connect", lifecycleStage: "POST_OPENING", module: "OPERATIONS" },
  { category: "HR", title: "Maintaining Staff Database", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "HR", title: "Staff Counsceling", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "HR", title: "Outlet Staff Documentation", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "HR", title: "Co-orporate staff Documentation", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "HR", title: "Leave Application File", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "HR", title: "Company Assets File Maintenance", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "HR", title: "Letters and formats for various uses", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "HR", title: "Birthday , Events & Milestone Posts& Letter", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "HR", title: "Organizing Corporate Activities", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "HR", title: "Office Stationary & First Aid Management", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "HR", title: "Outlet Training with Records", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "HR", title: "Outlet Staff Relations", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "HR", title: "Staff Full and Final", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "HR", title: "Salary Slip of Outlet", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "HR", title: "Policies , Memos & Announcements", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "HR", title: "Performance Evalution", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
  { category: "HR", title: "Company Asset Maintenance", lifecycleStage: "OPERATIONS_PREPARATION", module: "OPERATIONS" },
];
